name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: KeisukeYamashita/setup-release@v1.0.2
        id: kleat
        with:
          repository: spinnaker/kleat
          tag: v0.6.0

      - run: kleat version
      - run: echo "cache ${{ steps.kleat.outputs.restore-from-cache }}"

      - uses: KeisukeYamashita/setup-release@v1.0.2
        id: conftest
        with:
          repository: open-policy-agent/conftest
          arch: x86_64
          platform: Linux
          tag: v0.6.0

      - run: conftest --help
      - run: echo "cache ${{ steps.conftest.outputs.restore-from-cache }}"
