name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: KeisukeYamashita/setup-release@v1.0.2
        with:
          repository: spinnaker/kleat

      - run: kleat version

      - uses: KeisukeYamashita/setup-release@v1.0.2
        with:
          repository: open-policy-agent/conftest
          arch: x86_64
          platform: Linux

      - run: conftest --help
